"""empty message

Revision ID: 46f3fda9fe57
Revises: 0ddc960cfaf1
Create Date: 2026-04-22 10:52:01.757235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f3fda9fe57'
down_revision = '0ddc960cfaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname2', sa.String(length=32), nullable=False))
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.drop_index(batch_op.f('surname'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('surname'), ['surname'], unique=False)
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.drop_column('surname2')

    # ### end Alembic commands ###
