"""Add server_default

Revision ID: cc652fc8fb24
Revises: 3f3fa776b0db
Create Date: 2026-04-22 12:55:10.172410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc652fc8fb24'
down_revision = '3f3fa776b0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=32),
               server_default='Smirnov',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('surname',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###
